### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by marcalexiei** [marcalexiei/eslint-plugin-react-import#1]
### Basic setup implementation

- [x] add test CI (#3)
- [x] rewrite using program:exit (#2)
- [x] implement replace for all function using react adding `React.` prefix inside style rule (#5)
- [x] handle scenario with multiple imports and one satisfies the syntax option (#6)

### Setup plugin & config

- [x] create plugin and configs [ESLint reference](https://eslint.org/docs/latest/extend/plugins) (#8)
  - [x] create tests packages inside the repo and add a complete working example
- [x] add lint and format (#10)
  - [x] linter and follow this [guide](https://eslint.org/docs/latest/extend/plugins#linting-a-plugin)
  - [x] format using prettier

### Refine tests and add documentation
- [x] add configuration tests (#11)
  - [x] add both working and not working examples in tests
  - [x] add tests using vitest to ensure reported data is correct
- [x] add documentation inside GitHub via markdown files (use [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator)) (#12)
- [x] add `CONTRIBUTING.md`
  - [x] to make test working in local you should run build first
- [x] add `package.json` meta
  - `engines`
  - `peerDependencies`
  - `repository`
  - `homepage`
  - `bugs`
  - `keywords`

### Release management and release

- [x] publish
- [x] use changeset for automatic release (#13)
- [x] publish 1.0 with changeset

**Comment by marcalexiei** [comment]
Version 1.0 has been published successfully using changeset:

https://www.npmjs.com/package/eslint-plugin-react-import
